// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYFy1DeFdrlvNz22OY0vF0pLCUf9NqZL0',
    appId: '1:892470011334:web:aa0b4675a260f83299fec7',
    messagingSenderId: '892470011334',
    projectId: 'chatapp-881ae',
    authDomain: 'chatapp-881ae.firebaseapp.com',
    storageBucket: 'chatapp-881ae.appspot.com',
    measurementId: 'G-GKC4WD6H0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VWVq7axDfduuxKVqamIzt2iM1MvpjqA',
    appId: '1:892470011334:android:20e9740ecd07b67899fec7',
    messagingSenderId: '892470011334',
    projectId: 'chatapp-881ae',
    storageBucket: 'chatapp-881ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0p0FubqqSsvB49FprbmvC9f8T-6_mF8c',
    appId: '1:892470011334:ios:efb78e0a0062015699fec7',
    messagingSenderId: '892470011334',
    projectId: 'chatapp-881ae',
    storageBucket: 'chatapp-881ae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0p0FubqqSsvB49FprbmvC9f8T-6_mF8c',
    appId: '1:892470011334:ios:04513a910bb2185c99fec7',
    messagingSenderId: '892470011334',
    projectId: 'chatapp-881ae',
    storageBucket: 'chatapp-881ae.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
